domaintools/base_results.py

There seems to be a file descriptor leak, which comes up when a long-lived script makes many requests.  Not sure this is the perfect place to fix it, but it works for my use case.

Attempt to close sockets after use.

---

domaintools/exceptions.py

This allows users of logging/Logger ``.exception()`` to capture the reason for the failure for ex post facto investigations.

In exception, add the reason for the exception to the log message

---

domaintools_async/__init__.py
setup.py

Sorry, I had to de-genericize AIter due to having to defer actually getting the results until the first async context, namely `__anext__`.

Make 3.7 compatible, fix missing import, update to aiohttp 3 compatibility

---

setup.py

Fix a regression introduced in 941a85d2b7ad27f510c4109379e352bc4246cc0e which prevented the installation of domaintools-async on python 3.7.0/3.7.1.
The version check in setup.py was too strict with the use of the patch level identifier.
Some quick throwaway code used for validating the logic:
```
vers = [
(3, 7, 0),
(3, 7, 1),
(3, 6, 7),
(3, 6, 7),
(3, 6, 3),
(3, 6, 2),
(3, 6, 1),
(3, 6, 0),
(3, 5, 3),
(3, 5, 2),
(3, 5, 1),
(3, 5, 0),
(3, 4, 1),
(3, 4, 0),
(2, 7, 1),
(2, 7, 0),
(2, 6, 7),
(2, 6, 6),
(2, 6, 5),
]
_requires = ['requests']
_packages = ['domaintools']
for vertup in vers:
requires = list(_requires)
packages = list(_packages)
major, minor, patch = vertup
if major >= 3 and (minor > 5 or (minor == 5 and patch >= 2)):
packages.append('domaintools_async') …
```

Allow installation on python 3.7.0

---

setup.py

- Allow a wider range of aiohttp versions to be installed on python3.6+
- Remove the use of `requires` from the setup keywords list.  `install_requires` is the favored keyword per https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies.  This has been deprecated https://github.com/pypa/setuptools/pull/1541
Tested in 3.7.  Would recommend testing this across all support python versions.

aiohttp for python 3.6+ & setuptools depreciation

---

domaintools/base_results.py
domaintools/exceptions.py
tests/fixtures/vcr/test_iris_investigate.yaml
tests/settings.py

Currently iris_investigate api may fail for "414 uri too large error" due the size limit of GET method.  
- Changed GET to POST to support investigating up to 100 domains in an API call.
- Add an exception to notify error code 414.

use post for iris investigation api

---

setup.py

Quick fix to remove this error:
`/usr/local/lib/python3.7/site-packages/aiohttp/multipart.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Mapping, Sequence, deque`
Just need to kick aiohttp up above 3.6.0 for users of Python 3.5 and up.

Updated to >=3.6.0 aiohttp to clear deprecation warning.

---

domaintools/api.py
tests/fixtures/vcr/test_domain_search.yaml
tests/test_api.py

`domain_search` API expects space-separated `exclude_query` terms and not `|` separated. This diff aims to fix the fundamental issue in `delimited` function.
https://www.domaintools.com/resources/api-documentation/domain-search/

Fix delimited function. Added Unit Test.

---

domaintools/base_results.py
domaintools_async/__init__.py
tests/fixtures/vcr/test_limit_exceeded.yaml
tests/test_api.py

fixes #45 . 
In some cases, the DomainTools API does not respond with a 503 if the user has exceeded their search limits (eg > 5,000 entries in a result)...instead it returns json that says the user's limit has been exceeded. That case has to be caught in the result, so that the result object doesn't try to read results (there aren't any). This makes the result object raise a 503 exception in that case, since that seems to be the preferred way of signalling exceeded limits elsewhere in the API.

Catch response limit

---

domaintools/base_results.py

The proxies are captured in the API object construction at https://github.com/DomainTools/python_api/blob/master/domaintools/api.py#L52 
But they are not used in the HTTP calls made to api.domaintools.com. This commit fixes this bug.

Fix issue with using proxies

---

domaintools/base_results.py

The last commit was failing some tests due to a KeyError. This fixes
that problem by using .get() and providing a default.

fix KeyError is latest commit

---

domaintools/api.py

Updating Whois History to support the February 2021 changes. 
Documentation can be found here: https://www.domaintools.com/resources/api-documentation/whois-history/

Whois History API; add support for new parameters

---

domaintools/api.py
domaintools/cli.py

Fixes bug where users can't use available_api_calls on command line

---

domaintools/utils.py
tests/test_utils.py

Closes https://domaintools.atlassian.net/browse/ID-1389
example:
```
response = dt_api.iris_investigate('domaintools.com').response()
pivots = utils.get_pivots(response.get('results'), "")
```

ID-1389 Python Wrapper: Filter on counts

---

domaintools/cli/api.py
domaintools/cli/commands/accounts.py
domaintools/cli/commands/detects.py
domaintools/cli/commands/domains.py
domaintools/cli/commands/ips.py
domaintools/cli/commands/iris.py
domaintools/cli/commands/phisheye.py
domaintools/cli/main.py
domaintools/cli/utils.py

Changes:
- Change optional parameters from underscore to use dash instead, make it backward compatible with the prev version.
- Change iris_investigate kwargs parameter to use `-` instead of `_` to make it standard in other parameters.
- Adjust the argument parser to make it compatible in API params. 
- Add `-s` for short-hand command for `--source-file`.
- Add a max limit of 100 domains when using the  `--source-file` parameter.
- remove/strip colons on ssl hash input if colons happen to be present in the user-supplied certificate hash/fingerprint values.

[IDEV-282] Bugbash

---

domaintools/api.py
domaintools/base_results.py
domaintools/cli/api.py
domaintools/cli/commands/__init__.py
domaintools/cli/commands/feeds.py
domaintools/cli/constants.py
domaintools/cli/utils.py
domaintools/utils.py
setup.py
tests/fixtures/vcr/test_newly_active_domains_feed.yaml
tests/fixtures/vcr/test_newly_observed_domains_feed.yaml
tests/settings.py
tests/test_api.py
tox.ini

demo: https://www.loom.com/share/0592b7b7ffa04745af6d16cb1ceb7b1e

IDEV-1877 and IDEV-1886: Add nod and nad implemention

---

README.md
domaintools/api.py
domaintools/base_results.py
domaintools/cli/api.py
domaintools/cli/commands/feeds.py
domaintools/constants.py
domaintools/utils.py
domaintools_async/__init__.py
tests/fixtures/vcr/test_domainrdap_feed_not_api_header_auth.yaml
tests/test_api.py

IDEV-2011: add support for passing api key via header

---

README.md
domaintools/base_results.py
domaintools/cli/utils.py
domaintools/utils.py
tests/conftest.py
tests/test_api.py
tests/test_utils.py

README.md:
CLI help text:
UT test results:

IDEV-2013: Update help text and readme

---

domaintools/api.py
tests/e2e/scripts/test_e2e_runner.sh
tests/e2e/test_proxy.py
tests/e2e/test_ssl.py
tox.ini

IDEV-2050: Add proxy related tests

---

domaintools/api.py
tests/test_api.py
tests/test_cli.py
tox.ini

Remove support for md5 based signing
